POST http://localhost:3333/videos
Content-Type: application/json

{
    "title": "video node",
    "description": "Meu video",
    "duration": 180
}


### 
GET http://localhost:3333/videos


### 
PUT http://localhost:3333/videos/680de906-35e5-4cf3-8630-a335d91e1bc3
Content-Type: application/json

{
    "title": "video 13",
    "description": "Meu video",
    "duration": 180
}


### 
DELETE http://localhost:3333/videos/680de906-35e5-4cf3-8630-a335d91e1bc3